Outfit.create(name: "t-shirt", masculine: true, feminine: true, top: true, bottom: false, outerwear: false, shoe: false, range_start: 30, range_end: 90)
Outfit.create(name: "tank-top", masculine: true, feminine: true, top: true, bottom: false, outerwear: false, shoe: false, range_start: 65, range_end: 90)
Outfit.create(name: "long-sleeved shirt", masculine: true, feminine: true, top: true, bottom: false, outerwear: false, shoe: false, range_start: 45, range_end: 70)
Outfit.create(name: "sweater", masculine: true, feminine: true, top: true, bottom: false, outerwear: true, shoe: false, range_start: 30, range_end: 70)
Outfit.create(name: "jacket", masculine: true, feminine: true, top: true, bottom: false, outerwear: true, shoe: false, range_start: 30, range_end: 70)
Outfit.create(name: "jeans", masculine: true, feminine: true, top: false, bottom: true, outerwear: false, shoe: false, range_start: 30, range_end: 75)
Outfit.create(name: "shorts", masculine: true, feminine: true, top: false, bottom: true, outerwear: false, shoe: false, range_start: 70, range_end: 90)
Outfit.create(name: "skirt", masculine: false, feminine: true, top: false, bottom: true, outerwear: false, shoe: false, range_start: 65, range_end: 90)
Outfit.create(name: "sundress", masculine: false, feminine: true, top: false, bottom: true, outerwear: false, shoe: false, range_start: 65, range_end: 90)
Outfit.create(name: "sneakers", masculine: true, feminine: true, top: false, bottom: false, outerwear: false, shoe: true, range_start: 30, range_end: 80)
Outfit.create(name: "sandals", masculine: true, feminine: true, top: false, bottom: false, outerwear: false, shoe: true, range_start: 60, range_end: 90)
Outfit.create(name: "flip-flops", masculine: true, feminine: true, top: false, bottom: false, outerwear: false, shoe: true, range_start: 70, range_end: 90)
Outfit.create(name: "boots", masculine: true, feminine: true, top: false, bottom: false, outerwear: false, shoe: true, range_start: 30, range_end: 55)
